### ISSUE TITLE
Review - Be An Artist - QUIZ

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#108]
Please make changes using the "suggesting" mode in gdocs! :) 

https://docs.google.com/document/d/16i0thYIwPMDqziqfDfLAkEyXILHoUQiXMoKzPlcuD_I/edit

**Comment by sylvia-sable** [comment]
@lauradereynal I want you to review this one as there were a lot of changes from the script that happened during filming. I want to make sure the quiz reflects that. Please can you do this when you in the cafe with the good internet next?

**Comment by lauradereynal** [comment]
Good to go.
