### ISSUE TITLE
Final Question - Conflict Teaches - QUIZ

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#111]
https://docs.google.com/document/d/1IfVxOIdjVXel2u0otKDAxcEf9H5I8yN1i7ti-zzkE4I/edit

**Comment by sylvia-sable** [comment]
@lauradereynal I need your input on this quiz. There is one outstanding question that you can answer from filming. Please can you do this next time you are in the cafe with good internet? Thanks!

**Comment by sylvia-sable** [comment]
@lauradereynal I need you to input on this before I send to Bobby and Ryan to put into the app.

**Comment by lauradereynal** [comment]
sorryyyy just seeing this. I answered.
