### ISSUE TITLE
Review field tasks

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#118]
Hey Laura, 

I updated our plan for what to accomplish in the field with what I have been working towards these last few weeks. 

https://docs.google.com/spreadsheets/d/16GSJbRKMO7Pvdwq2n8PIVxw_d30WT6QWLeXwaAWyamw/edit#gid=2088895871

Can you please look it over and comment with any questions or changes (please don’t directly change or I might miss something – lots to juggle right now. 

 S

**Comment by secretrobotron** [comment]
@sylvia-sable it's not complete yet (still waiting on videos & quizzes), but @ryanwarsaw made a version of the app that you can test on a couple tablets. https://github.com/theirc/coach-erevu/releases/tag/v2.1

When you have a minute, can you try it out?
1) Download the APK from that link
2) Grab the videos from https://drive.google.com/drive/u/0/folders/1pyDRSH4Sg4FdKmpF8MJmKTLsA3wNw7Vg
3) Try running through a couple of videos and quizzes to make sure it flows the way you expect.
4) Help me make [this asset list](https://docs.google.com/spreadsheets/d/1sFxUA86lDFcEOxzXIAqb3SgXepy8X1V0mvS_HvL28-M/edit#gid=0) complete so we can finish the rest of the app

**Comment by lauradereynal** [comment]
@sylvia-sable I had a look and saw the comments you have in red 

Child protection officer: no need to hire someone full time, but ask Jerry himself, in person what he wants us to do. He has been aware of the project since last year and we engaged with his staff but there was turnover. I suspect it will look like 30% of someone's time.

Unless nicole does some magic in the next couple weeks, and all the videos are finished and compressed by @secretrobotron before you leave TZ, I suspect that Jacky will have to install the app on each tablet. So I think you should show her how to do that. 

@secretrobotron we are trying to get everything done before Sylvia leaves TZ, so she can make sure the apps and videos are working, but still waiting on nicole to finish these videos.

**Comment by secretrobotron** [comment]
Ok, no prob @lauradereynal. I have two laptops here that can compress those videos again overnight. @sylvia-sable Just let me know when they're ready in the Google Drive. Any insight on if Nicole is blocked/waiting?

**Comment by sylvia-sable** [comment]
Hey @secretrobotron @lauradereynal two things need to happen before we have final vids from Nicole 1) Nicole needs to input a pause screen into the videos. 2) the translators need to do a final check of the videos. 

For 1) I have sent her the info and I am just waitingto make the edits. I will poke her again to see how it's going. 

For 2) I can do this review using the  videos that are here: https://drive.google.com/drive/u/0/folders/1ePwbgkx5XpRhgpY5PndCawhmdQ1EBc-g 
These are not final and have the watermark on them, but I can use them to get the translators to do a final check. 

@secretrobotron can you please compress the videos at the link in #2 and send to me? If you send tonight I will download 

I am aiming to wrap these videos up with Nicole by Friday, compress them over weekend and get them on the tablets on Monday. If that happens then I can hand off the tablets with all the materials on them, ready for program launch after I leave. (Assuming of course we can get the quizzes on there too)

**Comment by secretrobotron** [comment]
👍 @sylvia-sable the compressed videos are available at https://drive.google.com/drive/u/0/folders/1pyDRSH4Sg4FdKmpF8MJmKTLsA3wNw7Vg but there are a couple missing. I'm going to compress them immediately so they should be ready for you when you wake up (or maybe tonight).

**Comment by sylvia-sable** [comment]
Thank you @secretrobotron I am going to check back when I wake up so I can download them all at once. 

Do you think it necessary to confirm these are the right ones with Nicole? It's hard for me to follow all the moving content. I am fine if they are the complete videos without the pause screens but if they are not the complete videos I fear driving the translators crazy.
