### ISSUE TITLE
Review - TOKENS

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#123]
https://docs.google.com/document/d/1aAejZMGQD4GzMtQi6_dP9DRzYXTSRdSsyWUY2WiHmHI/edit

Here is the language I want to use. We used something very similar to this in May and teachers liked it. They liked the specificity and how it was very clear what they needed to do in each activity (e.g. it guides them through the steps included in any SEL activity). I also took out references to the cards. 

I realize you might not have time to review this before i print and laminate, but if you do have time please review before EOD September 11. I will also comment below with the final design when Shirley sends it to me tomorrow so if you want to make tweaks to that you can! 

S

**Comment by sylvia-sable** [comment]
Just in time @lauradereynal I'll change.

**Comment by lauradereynal** [comment]
Perfect 😄 thank you   !
