### ISSUE TITLE
Finalize content.json files for CE quizzes

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#140]
Hi both, 

All final text to be used in the CE quizzes can be found here: 

https://drive.google.com/drive/folders/1FjRgSfKRjiky2eBmEF0JA4Pz4TZwdgJh?usp=sharing

**Can you please double check that all edits and comments have been addressed for ALL quizzes (I've left some small track changes - mostly formatting - and a few comments)?** 

I know Bobby already created most of the content.json files, but a double check on all would be much appreciated. 

I'm keen to download the app with these quizzes in it tomorrow if possible. 

Is this doable on your end?

This way I can test everything but the videos in the field on Thursday. 

Let me know!

Sylvia

**Comment by sylvia-sable** [comment]
Some updates from email: 

> Make sure all small text edits I made in the complete quizzes are incorporated into final json files (Bobby / Ryan)

**Bobby:** Ok to do this, but it needs a good chunk of time. Are you able to see the difference between what's already in the app and the changes you've made? In translating them to JSON, I removed much of the extraneous spacing and punctuation problems. But if there are other mistakes, like incorrect answers or spelling mistakes, we can hop on those. 

**Sylvia:** Great! Thank you for fixing up spacing and punctuation. I also did some of this using track changes in all the quizzes [here](https://drive.google.com/drive/folders/1FjRgSfKRjiky2eBmEF0JA4Pz4TZwdgJh?usp=sharing). Feel free to resolve the ones already addressed in your code. I will also have a look and do the same in the gdocs. I answered some questions you had for “Make a Statue Laugh” [here](https://docs.google.com/document/d/1xHhCMDp_9QyZbV--kq8pXqsU4k5prPpkrCwgcZGYEZU/edit?usp=drive_web&ouid=114399551986485910597). Lastly, [Conflict Teaches](https://docs.google.com/document/d/1IfVxOIdjVXel2u0otKDAxcEf9H5I8yN1i7ti-zzkE4I/edit?usp=drive_web&ouid=114399551986485910597) and [Be An Artist](https://docs.google.com/document/d/16i0thYIwPMDqziqfDfLAkEyXILHoUQiXMoKzPlcuD_I/edit?usp=drive_web&ouid=114399551986485910597) are ready.

**Comment by secretrobotron** [comment]
Ok, I think everything should be good after https://github.com/theirc/coach-erevu/pull/146 is incorporated into the APK. @sylvia-sable I tried to separate the changes you made from the ones I had already made in transferring stuff to JSON, but I can't be 100% sure I got it all. Are you spending some time with a translator to make sure all the content is solid **within the app**?

**Comment by sylvia-sable** [comment]
@secretrobotron yes I am going to sit with them and resolve all final comments at that time. I'm sitting with them tomorrow (Friday).
