### ISSUE TITLE
Conduct final video edits for final upload in app

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#141]
Video edits identified from the translators' final check can be found here: 

https://docs.google.com/document/d/1MdisiWT7ALazvHcvNW9ltZA3_-GdCFNf0SqkFgvEUE0/edit

In addition to these edits, we need to add in the correct pause screen 2x in each video following the instructions at the link. The pause screen should display for 20 seconds minimum and be inserted 
1) after the classroom demo and 
2) after the do's / don'ts and Q&A + before Conclusion 
**Is this order of scenes still correct Laura? Can you please double check that Nicole put them in the right places?**

https://docs.google.com/document/d/1rXGBQL-2P4WNEeYeYW_0HohxNIlt9GBz2Pwo2HYa_Mk/edit

Don't hesitate to reach out for help / clarifications!

**Comment by ryanwarsaw** [comment]
I assume if the final videos are in the app, we can now close this? @sylvia-sable

**Comment by lauradereynal** [comment]
yep, I finished them
