### ISSUE TITLE
Release Tunakujenga APK

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#142]
Assets are here: 

https://docs.google.com/spreadsheets/d/18CX5_tWaYkfjuWSCdcFuUl5kGiLAp-LVv_YTJfG2Sbw/edit#gid=221070936

We still need to create the content.json files for the quizzes, input compressed videos, and finalize any outstanding issues (not sure what these are, maybe @secretrobotron and @ryanwarsaw can weigh in?)

@lauradereynal  is sending logo, app icon, and color palette

**Comment by secretrobotron** [comment]
@sylvia-sable see https://github.com/ryanwarsaw/Tunakujenga
