### ISSUE TITLE
Colors - level boxes

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#149]
The last 3 levels (level 3, level 4, level 5) are all the same color. Can we make them different / a gradient? Does @lauradereynal need to send more colors?

**Comment by secretrobotron** [comment]
This isn't too bad. What do you think?

<img width="405" alt="screenshot 2018-09-22 17 26 55" src="https://user-images.githubusercontent.com/403231/45921888-b8354d80-be8c-11e8-9949-898263f18a02.png">

**Comment by sylvia-sable** [comment]
Looks great! @secretrobotron
