### ISSUE TITLE
Add Healing Classroom Videos

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#164]
@lauradereynal we need to think about how to add in healing classroom videos. Without an accompanying weekly schedule the teachers won't know which weeks to watch a SEL activity + Quiz and which weeks to watch just a SEL activity. 

The sequencing of activites and weeks can be found here: https://docs.google.com/spreadsheets/d/1sFxUA86lDFcEOxzXIAqb3SgXepy8X1V0mvS_HvL28-M/edit#gid=221070936

Can you talk to @secretrobotron and @ryanwarsaw about this and decide how to carry forward?

**Comment by secretrobotron** [comment]
@ryanwarsaw can an activity have a video but not a quiz?

**Comment by secretrobotron** [comment]
😭 ok, i just checked. we can't. If a video doesn't have a quiz to go along with it, we need to fix the app.

@sylvia-sable you want these to be along-side the other activities, right? e.g.
##### Level 1
  - Activity 1 (SEL Activity)
    - Video 1
    - Quiz 1
 - Activity 2 (Healing Classroom)
   - Video 2
...

**Comment by ryanwarsaw** [comment]
Well I can fix that pretty easily, so I'll make that change.

**Comment by secretrobotron** [comment]
Oh! Haha, here you go: https://github.com/theirc/coach-erevu/pull/170

**Comment by ryanwarsaw** [comment]
Fixed in #172, you can add either a quiz or a video, or both to a topic and the app handles it accordingly. This means you can have a topic with only a video, or only a quiz.

**Comment by sylvia-sable** [comment]
@secretrobotron @ryanwarsaw here are [final healing classroom videos in Kirundi](https://drive.google.com/drive/folders/1LkyiviT6sloHMdS0qhhWewO9TDtm5Iwk?usp=sharing). 

They need to be compressed and uploaded [here](https://drive.google.com/drive/folders/1X3fxENKmhUbxi4dTiAsY2FGO619yIEdO?usp=sharing). Let me know if you have any questions! 

(video file locations also in [CE asset list](https://docs.google.com/spreadsheets/d/1sFxUA86lDFcEOxzXIAqb3SgXepy8X1V0mvS_HvL28-M/edit#gid=2466508))

@lauradereynal

**Comment by ryanwarsaw** [comment]
@secretrobotron These videos are in the app and compressed, they aren't in the content file because I didn't know where to put them (more specifically the translations and what not??), please advise.

**Comment by secretrobotron** [comment]
Hey, @ryanwarsaw:

* Don't worry about translations for now. I put the english versions in the content file in  #184 (cc @lauradereynal).
* In case it's useful, I recompressed the files. I just didn't read what you wrote up here before compressing them. (hehe) They're here: https://drive.google.com/drive/folders/1X3fxENKmhUbxi4dTiAsY2FGO619yIEdO
* There's an LFS quota problem on this repo now, I think. I'm not able to pull down the assets. Have to use `GIT_LFS_SKIP_SMUDGE`.

**Comment by secretrobotron** [comment]
> There's an LFS quota problem on this repo now, I think. I'm not able to pull down the assets. Have to use GIT_LFS_SKIP_SMUDGE.

Ok, I figured out how to effectively ignore LFS when pushing/pulling. When you actually want to build the app though, a person would have to run LFS on purpose, and have all the files local, right?

**Comment by ryanwarsaw** [comment]
@secretrobotron LFS is a separate component from git, so to just clone the project and none of the LFS files you can use that flag, then use `git lfs pull` to download just those files whenever you need them (note: You must install git LFS, you can do it via brew: `brew install git-lfs`).

If you don't pass that parameter, the default operation is it'll attempt to download LFS files on clone, which will take a while. I haven't had any issues, it's weird that you have though.
