### ISSUE TITLE
Translator review Healing Classrooms dub

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#179]

**Comment by lauradereynal** [comment]
@sylvia-sable are you planning for them to review soon ? Should we wait for them to give us a go before we package a new APK ?

**Comment by sylvia-sable** [comment]
No, do not wait for translator review. The review is really a conservative thing. I want to see how good the quality is and I can't speak kirundi so i want the translators to check. If there are big mistakes obviously we'll catch them and fix them using this review too.  @lauradereynal

**Comment by sylvia-sable** [comment]
Finished and no issues!
