### ISSUE TITLE
Send Sylvia link with all final compressed videos

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#180]
@secretrobotron @lauradereynal This should include: 

- Introduction Video
-SEL Actviity Videos
-Healing Classroom Videos

I will share this with our team in the field with instructions for how to put on the app.

**Comment by lauradereynal** [comment]
@secretrobotron @ryanwarsaw Are we going to package the APK including the videos, or excluding the videos ? 

In other words, are we expecting the people in the office to add the videos by themselves?

**Comment by ryanwarsaw** [comment]
@lauradereynal i can give you both and then you can decide which one you want to do? Also SEL videos were compressed I sent the google drive link yesterday @sylvia-sable. Will work on compressing the healing classroom videos, not sure about the introduction video.

**Comment by sylvia-sable** [comment]
@ryanwarsaw @secretrobotron @lauradereynal I like having both options: 1) APK with videos and 2) APK and videos separately. Can you send me 2 compressed video links for CE and TKJ when complete? The CE needs introduction, SEL activity videos, and healing classrooms. TKJ only needs SEL activities. 

I am boarding a 14 hour flight but will check in after that.

**Comment by secretrobotron** [comment]
@sylvia-sable all final compressed videos for coach erevu are available here: https://drive.google.com/drive/folders/17Olyuxy997e4SrRDfILQhHQfl4uoPM5e
