### ISSUE TITLE
Change healing classroom video titles to Kirundi

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#189]
@ryanwarsaw the video titles for the healing classrooms videos need to be in Kirundi. 

Classroom routines: Nkuko vyama mw’isomero 
Expressing appreciation: Kwerekana ugushima
Working in a group: Gukorera mu murwi  
Questions: Ibibazo

**Comment by lauradereynal** [comment]
@ryanwarsaw Can you please change these titles before you release the next APK ? 

Just to avoid wasting your own time.
