### ISSUE TITLE
Intro Quiz:  Change text in final pop-up box

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#191]
The text in the pop-up box at the end of the quiz is not correct. 

Right now it is the same as all the other quizzes. 

Instead it needs to say: 

**Mwakoze gukorera hamwe aka kabazo nk’umurwi!**

You can also find it in question 8 here in the quiz: https://docs.google.com/document/d/1E0lXQVz5Yn9HpQQ02xWn3ghxPVjZstEcB_PG3Lgus00/edit

**Comment by ryanwarsaw** [comment]
Currently this is hardcoded.

**Comment by sylvia-sable** [comment]
@ryanwarsaw @secretrobotron does hardcoded mean that we could not update it in the new APK?

**Comment by ryanwarsaw** [comment]
I fixed it in the new version please verify.

**Comment by sylvia-sable** [comment]
@ryanwarsaw it is changed! Thanks for clarifying!
