### ISSUE TITLE
Review "See What I Did There?" (Brain Building: 1/5)

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#62]
https://docs.google.com/document/d/1rQ4fH7XIJnOz7FsJcJ3VRdp7DOnIF2_bxs_M3lqOEms/edit

Review: 
>Content (do's / don'ts; wording of do's / don'ts and suggestions for simplifying; Q+A)
>My comments to Randa (do you agree / disagree)
>Add your own comments to Randa
>Anything else you see / think of!

**Comment by lauradereynal** [comment]
Done @sylvia-sable
