### ISSUE TITLE
create color palette for monthly system

### ISSUE THREAD

**Issue by lauradereynal** [theirc/coach-erevu#68]

**Comment by secretrobotron** [comment]
@ryanwarsaw has very handily made the color palette easy to change. We just need a few hex codes to put in the `content.json` file. If the team can decide what they should be, and drops those hex codes here, we can put them in. 👏

**Comment by lauradereynal** [comment]
Based on #86 let's use the following 

* Level 1 #45B39D 
* Level 2 #117A65  
* Level 3 #1A5276
