### ISSUE TITLE
Consider remote access options 

### ISSUE THREAD

**Issue by ryanwarsaw** [theirc/coach-erevu#69]
Consider an option to remote access the tablets in Tanzania, should an issue arise that requires development assistance.

**Comment by secretrobotron** [comment]
👍 let's research our options. I think there's a good Samsung remote access™ thing, but I'm not sure. If there is, we should take the opportunity to test how feasible it is as a help tool in the internet conditions the tablets are likely to be in. We can coordinate with @lauradereynal and @sylvia-sable to try, perhaps.

@lauradereynal @sylvia-sable ideally, we can prepare as much as possible ahead of time to avoid running into lots of situations where remote access is even required. Do you know when the app is being deployed? And, if so, do we have some time to run tests in conditions that will be as close to real-world as possible?

**Comment by sylvia-sable** [comment]
@secretrobotron @ryanwarsaw 
Some dates: 
> the app needs to be in use starting Oct. 22
>I will be in Tanzania from September 10 - 21. Let's aim to test then? 
>If you prefer sooner, Laura will be in Tanzania from August 7 to August 17, but I imagine you might not be ready that soon?

**Comment by lauradereynal** [comment]
in addition, the tablets will need to fly to TZ with @sylvia-sable on September 10th, so everything should be perfect for this deadline. 

If you want to test any remote controll thing right now @secretrobotron I have the tablet in my hands and happy to install any app

**Comment by lauradereynal** [comment]
I don't think we are working on this anymore. Closing.
