### ISSUE TITLE
Language consistency accross all videos 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/coach-erevu#75]
@sylvia-sable please do a final read and search for the following languages:
* Replace do's and dont's by "the effective teacher's guide"
* Replace all "games" by "**activitiy**"
* When we changed activity names, make sure the new name is used accross the page

**Comment by lauradereynal** [comment]
Hey @sylvia-sable did you get this done ? If yes, close the ticket when you see this message, if not, let me know and I'll do this here.

**Comment by sylvia-sable** [comment]
Done @lauradereynal
