### ISSUE TITLE
Review Quiz Template

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#87]
https://docs.google.com/document/d/110f_Xpnh60PWRYkA61ekU-r-lWE-JvvyAa7MQeX7hUI/edit

Please provide feedback. Once you review, I will finalize and send to Randa + Rena for approval. I will start mass producing the quizzes before hearing back from Randa + Rena to make sure they are done by Wednesday.

**Comment by lauradereynal** [comment]
All good to go. 👍
